Started!
Hooking
Sourcing
Sourced
declare -x BASH_ENV="/sw/arcts/centos7/lmod/lmod/init/bash"
declare -x CLUSTER_NAME="greatlakes"
declare -x CONDA_DEFAULT_ENV="lqam"
declare -x CONDA_EXE="/home/ruoyaow/miniconda3/bin/conda"
declare -x CONDA_PREFIX="/home/ruoyaow/miniconda3/envs/lqam"
declare -x CONDA_PREFIX_1="/home/ruoyaow/miniconda3"
declare -x CONDA_PROMPT_MODIFIER="(lqam) "
declare -x CONDA_PYTHON_EXE="/home/ruoyaow/miniconda3/bin/python"
declare -x CONDA_SHLVL="2"
declare -x CUDA_PATH="/home/ruoyaow/miniconda3/envs/lqam"
declare -x CUDA_VISIBLE_DEVICES="0"
declare -x CVS_RSH="ssh"
declare -x ENVIRONMENT="BATCH"
declare -x GPU_DEVICE_ORDINAL="0"
declare -x HISTCONTROL="ignoredups"
declare -x HISTSIZE="1000"
declare -x HOME="/home/ruoyaow"
declare -x HOSTNAME="gl1010"
declare -x KDEDIRS="/usr"
declare -x KRB5CCNAME="FILE:/tmp/krb5cc_114164170_ZgdCGD"
declare -x LANG="en_US.UTF-8"
declare -x LD_LIBRARY_PATH="/opt/slurm/lib64:"
declare -x LESSOPEN="||/usr/bin/lesspipe.sh %s"
declare -x LMOD_AVAIL_STYLE="grouped"
declare -x LMOD_CMD="/sw/arcts/centos7/lmod/lmod/libexec/lmod"
declare -x LMOD_DIR="/sw/arcts/centos7/lmod/lmod/libexec"
declare -x LMOD_PACKAGE_PATH="/sw/arcts/centos7/lmod"
declare -x LMOD_PKG="/sw/arcts/centos7/lmod/lmod"
declare -x LMOD_SETTARG_FULL_SUPPORT="no"
declare -x LMOD_VERSION="7.8.9"
declare -x LMOD_sys="Linux"
declare -x LOGNAME="ruoyaow"
declare -x LS_COLORS="rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:"
declare -x MAIL="/var/spool/mail/ruoyaow"
declare -x MANPATH="/sw/arcts/centos7/lmod/lmod/share/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man:/opt/ddn/ime/share/man:/opt/ddn/ime/share/man:/opt/slurm/share/man/:/opt/TurboVNC/man/"
declare -x MODULEPATH="/sw/arcts/centos7/lmod/lmod/modulefiles/Core:/sw/arcts/centos7/modulefiles/Core:/sw/arc/centos7/modulefiles/Core:/sw/arcts/centos7/modulefiles/Collections"
declare -x MODULEPATH_ROOT="/sw/arcts/centos7/modulefiles"
declare -x MODULESHOME="/sw/arcts/centos7/lmod/lmod"
declare -x OLDPWD
declare -x PATH="/home/ruoyaow/miniconda3/envs/lqam/bin:/home/ruoyaow/miniconda3/condabin:/opt/TurboVNC/bin:/opt/slurm/bin:/opt/slurm/sbin:/usr/lib64/qt-3.3/bin:/sw/arcts/centos7/usertools/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lpp/mmfs/bin:/opt/ddn/ime/bin:/home/ruoyaow/.local/bin:/home/ruoyaow/bin"
declare -x PWD="/home/ruoyaow/LifeQA-methodology"
declare -x QTDIR="/usr/lib64/qt-3.3"
declare -x QTINC="/usr/lib64/qt-3.3/include"
declare -x QTLIB="/usr/lib64/qt-3.3/lib"
declare -x QT_GRAPHICSSYSTEM_CHECKED="1"
declare -x QT_PLUGIN_PATH="/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins"
declare -x ROCR_VISIBLE_DEVICES="0"
declare -x SHELL="/bin/bash"
declare -x SHLVL="2"
declare -x SLURMD_NODENAME="gl1010"
declare -x SLURM_CLUSTER_NAME="greatlakes"
declare -x SLURM_CONF="/opt/slurm/etc/slurm.conf"
declare -x SLURM_CPUS_ON_NODE="20"
declare -x SLURM_CPUS_PER_TASK="20"
declare -x SLURM_GTIDS="0"
declare -x SLURM_JOBID="17506878"
declare -x SLURM_JOB_ACCOUNT="mihalcea1"
declare -x SLURM_JOB_CPUS_PER_NODE="20"
declare -x SLURM_JOB_GID="114164170"
declare -x SLURM_JOB_GPUS="0"
declare -x SLURM_JOB_ID="17506878"
declare -x SLURM_JOB_NAME="t5_i3d"
declare -x SLURM_JOB_NODELIST="gl1010"
declare -x SLURM_JOB_NUM_NODES="1"
declare -x SLURM_JOB_PARTITION="gpu"
declare -x SLURM_JOB_QOS="normal"
declare -x SLURM_JOB_UID="114164170"
declare -x SLURM_JOB_USER="ruoyaow"
declare -x SLURM_LOCALID="0"
declare -x SLURM_MEM_PER_NODE="51200"
declare -x SLURM_NNODES="1"
declare -x SLURM_NODEID="0"
declare -x SLURM_NODELIST="gl1010"
declare -x SLURM_NODE_ALIASES="(null)"
declare -x SLURM_PRIO_PROCESS="0"
declare -x SLURM_PROCID="0"
declare -x SLURM_SUBMIT_DIR="/home/ruoyaow/LifeQA-methodology"
declare -x SLURM_SUBMIT_HOST="gl-login1.arc-ts.umich.edu"
declare -x SLURM_TASKS_PER_NODE="1"
declare -x SLURM_TASK_PID="218823"
declare -x SLURM_TOPOLOGY_ADDR="gl1010"
declare -x SLURM_TOPOLOGY_ADDR_PATTERN="node"
declare -x SLURM_WORKING_CLUSTER="greatlakes:glctld:6817:8960:109"
declare -x SQUEUE_FORMAT="%.18i %.9P %.8j %.8u %.8a %.2t %.10M %.6D %R"
declare -x SSH_AGENT_PID="47000"
declare -x SSH_ASKPASS="/usr/libexec/openssh/gnome-ssh-askpass"
declare -x SSH_AUTH_SOCK="/tmp/ssh-ANykr0d3GLYB/agent.46998"
declare -x SSH_CLIENT="141.213.168.10 44570 22"
declare -x SSH_CONNECTION="141.213.168.10 44570 141.211.192.38 22"
declare -x SSH_TTY="/dev/pts/144"
declare -x TERM="xterm-256color"
declare -x TMOUT="86400"
declare -x TMPDIR="/tmp"
declare -x USER="ruoyaow"
declare -x XDG_DATA_DIRS="/home/ruoyaow/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share"
declare -x XDG_RUNTIME_DIR="/run/user/114164170"
declare -x XDG_SESSION_ID="27115"
declare -x _CE_CONDA=""
declare -x _CE_M=""
Global seed set to 42
Some weights of T5AndVisual were not initialized from the model checkpoint at t5-base and are newly initialized: ['encoder.embed_video.weight', 'encoder.embed_video.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Set SLURM handle signals.

  | Name                | Type                     | Params
-----------------------------------------------------------------
0 | t5_pretrained_model | T5AndVisual              | 223 M 
1 | accuracy            | AlmostExactMatchAccuracy | 0     
2 | accuracy_many       | AlmostExactMatchAccuracy | 0     
3 | F1Scores            | F1Scores                 | 0     
4 | F1Scores_labels     | F1Scores                 | 0     
-----------------------------------------------------------------
223 M     Trainable params
0         Non-trainable params
223 M     Total params
Connection error occurred while trying to fetch ETag for https://drive.google.com/uc?id=1rglAizpxanVDejDP6HuCM7UaXLxEQwnK&export=download. Will attempt to use latest cached version of resource
Connection failed while trying to fetch ETag, and no cached version of https://drive.google.com/uc?id=1rglAizpxanVDejDP6HuCM7UaXLxEQwnK&export=download could be found
Traceback (most recent call last):
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2ac6bf3ba970>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1rglAizpxanVDejDP6HuCM7UaXLxEQwnK&export=download (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ac6bf3ba970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/run_model.py", line 126, in <module>
    main()
  File "scripts/run_model.py", line 109, in main
    trainer.fit(filler, datamodule=data_module)
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 57, in train
    return self.train_or_test()
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in train
    self.run_sanity_check(self.get_model())
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 720, in run_sanity_check
    self.reset_val_dataloader(ref_model)
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 287, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 207, in _reset_eval_dataloader
    dataloaders = self.request_dataloader(getattr(model, loader_name))
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 310, in request_dataloader
    dataloader = dataloader_fx()
  File "/home/ruoyaow/LifeQA-methodology/lqam/methods/dataset.py", line 125, in val_dataloader
    return self._dataloader(self.val_data_path, batch_size=self.eval_batch_size, train=False)
  File "/home/ruoyaow/LifeQA-methodology/lqam/methods/dataset.py", line 114, in _dataloader
    dataset = QGenDataset(data_path, tokenizer=self.tokenizer, visual_data_dir=self.visual_data_dir)
  File "/home/ruoyaow/LifeQA-methodology/lqam/methods/dataset.py", line 33, in __init__
    with open(cached_path(data_path), 'r') as f:
  File "/home/ruoyaow/LifeQA-methodology/lqam/util/file_utils.py", line 153, in cached_path
    file_path = get_from_cache(url_or_filename, cache_dir)
  File "/home/ruoyaow/LifeQA-methodology/lqam/util/file_utils.py", line 411, in get_from_cache
    etag = _http_etag(url)
  File "/home/ruoyaow/LifeQA-methodology/lqam/util/file_utils.py", line 321, in _http_etag
    response = session.head(url, allow_redirects=True, timeout=TIMEOUT)
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/requests/sessions.py", line 577, in head
    return self.request('HEAD', url, **kwargs)
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ruoyaow/miniconda3/envs/lqam/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1rglAizpxanVDejDP6HuCM7UaXLxEQwnK&export=download (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ac6bf3ba970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Done
